export const ADD_PRODUCT_QUICKVIEW = "ADD_PRODUCT_QUICKVIEW";
export const ADD_PRODUCT_RECENTVIEW = "ADD_PRODUCT_RECENTVIEW";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const APPLY_COUPON = "APPLY_COUPON";
